### ISSUE TITLE
docker pull openbmp/collector throws error 'Error response from daemon: manifest for openbmp/collector:latest not found: manifest unknown: manifest unknown'

### ISSUE THREAD

**Issue by Djethva** [OpenBMP/obmp-docker#10]
Hello,
Not sure if I am doing something wrong. But when trying to pull image I get below response.
```
root@google-pr-bmp1:~# docker pull openbmp/collector
Using default tag: latest
Error response from daemon: manifest for openbmp/collector:latest not found: manifest unknown: manifest unknown
```
Instead pulling a particular version works fine
```
root@google-pr-bmp1:~# docker pull openbmp/collector:2.1.0
2.1.0: Pulling from openbmp/collector
5eb5b503b376: Pull complete
fe3c6f8624c4: Pull complete
1ff68dd5f599: Pull complete
fb8500ea73b5: Pull complete
f92c91e490e7: Pull complete
6bf2344a7c51: Pull complete
526e5dfa9e59: Pull complete
417a1ff5f816: Pull complete
98931b0c2407: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:8b1d0e9daefb813c0bd652b273c884c7859281a1730d983052dd0748a43bfb96
Status: Downloaded newer image for openbmp/collector:2.1.0
docker.io/openbmp/collector:2.1.0
root@google-pr-bmp1:~#
```

**Comment by TimEvens** [comment]
I removed the latest tag because a layer issue.  I'll add it back with version 2.1.0.   

2.1.0 was not complete yet... but i have updated it. You'll need to remove your current 2.1.0 docker images.  You can do that using ```docker rmi openbmp/...```

**Comment by TimEvens** [comment]
I have updated all the latest tags. You should see them now.  Please let me know if you run into any further issues. I'll close this issue in a few days if I don't hear back. 

I have changed the docker-compose file to no longer use latest.  It now uses specific versions.  I would like to move away from using latest as it's a bit of a pain to update images locally that have the same tag.  For example, update your latest image to the actual latest image.

**Comment by Djethva** [comment]
Thanks Tim.
I don't see `      - MEM=64                                                     # Set MEM to at least 2GB but ideally >16GB` under `psql` anymore in docker-compose.yml. Is it intended?

**Comment by TimEvens** [comment]
It's not needed unless you want to restrict it to be less than system/vm available memory.  That setting was being overwritten by the TimescaleDB tune script. It's been that way for a while now. I removed it because it wasn't working.  Instead, you can use ```TS_TUNE_MEMORY=<n>GB``` or let it auto detect.  I've updated documentation to call this out.   

https://www.openbmp.org/install_config/containers.html#timescaledb-tune-script

**Comment by Djethva** [comment]
Thanks Tim. Since the docker pull is now working. I would like to close the issue
```
root@google-pr-bmp1:~# docker pull openbmp/postgre
Using default tag: latest
Error response from daemon: pull access denied for openbmp/postgre, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
root@google-pr-bmp1:~# docker pull openbmp/postgres
Using default tag: latest
latest: Pulling from openbmp/postgres
59bf1c3509f3: Already exists
c50e01d57241: Pull complete
a0646b0f1ead: Pull complete
7433e5151e0c: Pull complete
8854018388d9: Pull complete
8de463f7fd19: Pull complete
b39ee18abab9: Pull complete
0672f14af61b: Pull complete
45a517da53e6: Pull complete
65d3b2ea54de: Pull complete
90fd232f6975: Pull complete
7b16ff2664b4: Pull complete
2478a80aa252: Pull complete
b1b26ed868c2: Pull complete
5edde4b7e0d0: Pull complete
d37cebebb97d: Pull complete
```
