### ISSUE TITLE
Missing relation in psql

### ISSUE THREAD

**Issue by BouchardClaude** [OpenBMP/obmp-docker#11]
I'm having issues with missing link in the database.
It look like a table is not getting generated as start.

`obmp-psql       | 2022-03-07 03:48:28.657 UTC [51] ERROR:  relation "peer_event_log" does not exist at character 13
obmp-psql       | 2022-03-07 03:48:28.657 UTC [51] QUERY:  INSERT INTO peer_event_log (state,peer_hash_id,local_ip,local_bgp_id,local_port,local_hold_time,
obmp-psql       |                                           local_asn,remote_port,remote_hold_time,
obmp-psql       |                                           sent_capabilities,recv_capabilities,geo_ip_start,timestamp)
obmp-psql       |                       VALUES (new.state,new.hash_id,new.local_ip,new.local_bgp_id,new.local_port,new.local_hold_time,
obmp-psql       |                               new.local_asn,new.remote_port,new.remote_hold_time,
obmp-psql       |                               new.sent_capabilities,new.recv_capabilities,new.geo_ip_start, new.timestamp)
obmp-psql       | 2022-03-07 03:48:28.657 UTC [51] CONTEXT:  PL/pgSQL function t_bgp_peers() line 11 at SQL statement
`

here is a view of what tables are created 
![image](https://user-images.githubusercontent.com/22671885/156964861-f6a86509-c89c-4549-8a43-38801a329113.png)

Docker-compose file : 2.1.0
Docker version 20.10.7
Docker Compose version v2.3.0

Setup was working before I upgrade docker and restarted all docker, so I guess something had changed

**Comment by TimEvens** [comment]
Based on your image of tables, you are missing all the timeseries ones. ```peer_event_log``` is one of them, but there are several others, for example ```ip_rib_log```, ```l3vpn_rib_log```, ```stats_chg_*```, ...

Can you run the below and validate that you have **timeseries** tablespace? 

```
openbmp=# SELECT * FROM pg_tablespace;
  oid  |  spcname   | spcowner | spcacl | spcoptions
-------+------------+----------+--------+------------
  1663 | pg_default |       10 |        |
  1664 | pg_global  |       10 |        |
 18111 | timeseries |       10 |        |
(3 rows)
```

The ```timeseries``` **tablespace** is created in the ```openbmp/postgres``` container (**obmp-postgres**).  This is done via [obmp-docker/postgres/Dockerfile Line 45](https://github.com/OpenBMP/obmp-docker/blob/main/postgres/Dockerfile#L45).   If you are running postgres via another deployment, then you will need to create the tablespace.   This is not created by the ```obmp-docker/psql-app``` because the timeseries path/location is specific to the postgres deployment. The postgres deployment/install defines the location, such as using a different volume, for timeseries.

**Comment by BouchardClaude** [comment]
While troubleshooting I just realised psql was complaining about permission to create /ts/data folder.  So maybe the issue is related to my setup . I am using the psql from the same deployment, so I'm not sure if its my setup only. 
I fixed it by doing  a chown inside the docker for now. Will investigate this and report after deploying on a new setup

thx for the help

**Comment by TimEvens** [comment]
I have added a troubleshooting doc for this.  Check out https://www.openbmp.org/troubleshooting/postgres.html. It could have been an issue when you created the directories.   Normally you should not have to do that within the container.  It should be done at that the $OBMP_DATA_ROOT level when starting with a fresh install.  

Please let me know what we can do better to improve the documentation.  Maybe add a note or step to avoid a permission problem?.?

**Comment by BouchardClaude** [comment]
thanks. the Doc was helpful and resolved my issue. The problem was I was under the impression that the OBMP_DATA_ROOT was set in a .env file.. so I forgot to set it again while restarting the setup..( making it pointing to / instead of /var/openbmp) 
We can close the issue . Good thing you made it clear in the doc how to reset the db..
Happy to see this projet is still maintained ;)
