### ISSUE TITLE
[psql-app] rpki integration

### ISSUE THREAD

**Issue by purifp** [OpenBMP/obmp-docker#15]
I have installed the version 2.1.1 but the rpki integration seems not to work:
openbmp/postgres:2.1.1
openbmp/collector:2.1.1    
openbmp/psql-app:2.1.1 

I have data the roas in the table "rpki_validator" and our bgp prefixes "ip_rib" but the field rpki_origin_as is empty in table "global_ip_rib", i think that the script that update this table fails. I also  have empty the table "alert".
Does anyone have rpki integration working?

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/36138518/170688754-7552dc9f-4d22-48fe-87b5-400b7dc4e1ec.png">
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/36138518/170688786-1855a923-c452-41d4-80f3-ad5230397dd5.png">

perhaps I have not understood how the integration with rpki works, I hope to see if I have prefixes with ASN or MASK different from what is published in the roas

thanks in advance
Puri

**Comment by TimEvens** [comment]
There were problems with the function that updated the global RIB.  This has now been fixed in 2.2.0 release, which I'm about to finish.

**Comment by purifp** [comment]
Any estimated date for the new release? thank you so much.

**Comment by TimEvens** [comment]
It has been released. Thanks t should be working now in the latest version.

**Comment by TimEvens** [comment]
Closing, this was fixed in 2.2.0. Please re-open if you are still having issues.
