### ISSUE TITLE
Fixing chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted

### ISSUE THREAD

**Issue by v1shnya** [OpenBMP/obmp-docker#17]
As a proposal, below is a solution to the error - chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted - use of local Docker Volumes
https://forums.docker.com/t/create-local-volume-with-custom-mount-options/117924

volumes:
&nbsp;data-volume:
&nbsp;&nbsp;driver_opts:
&nbsp;&nbsp;&nbsp;&nbsp;type: none
&nbsp;&nbsp;&nbsp;&nbsp;device: ${OBMP_DATA_ROOT}/postgres/data 
&nbsp;&nbsp;&nbsp;&nbsp;o: bind
&nbsp;ts-volume:
&nbsp;&nbsp;driver_opts:
&nbsp;&nbsp;&nbsp;&nbsp;type: none
&nbsp;&nbsp;&nbsp;&nbsp;device: ${OBMP_DATA_ROOT}/postgres/ts 
&nbsp;&nbsp;&nbsp;&nbsp;o: bind

psql:
   ........
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ts-volume:/var/lib/postgresql/ts

**Comment by TimEvens** [comment]
Thank you for the info. I have updated the compose file to include this change. this does appear to fix the issue with perms.

**Comment by TimEvens** [comment]
Fixed.
