### ISSUE TITLE
psql-app icontainer errors + env vars not working.

### ISSUE THREAD

**Issue by vkratsberg** [OpenBMP/obmp-docker#2]
Hello, 

Thank you for putting together a great app.  I encountered some issues with psql-app containter when trying to connect to on-prem database. 

1.  Typo when running /usr/sbin/run 
```
root@openbmp-corp-psql-app-7d7dbbd978-999rj:/tmp# /usr/sbin/run
/usr/sbin/run: line 13: exprot: command not found
```

2.  Container doesn't seem to use provided env vars correctly.
```
root@openbmp-corp-psql-app-7d7dbbd978-999rj:/tmp# printenv | grep POST
POSTGRES_HOST=service-postgres002.eqx.dal.corp
POSTGRES_PORT=6432
POSTGRES_USER=openbmp
POSTGRES_DB=openbmp-dal
```

Config portion of _config/obmp-psql.yml looks like this:

```
postgres:
  host    : "service-postgres002.eqx.dal.corp"
  db_name : "openbmp"
  username: "openbmp"
  password: "openbmp"
```

Seems like only POSTGRES_HOST env var worked.  
I see why.  Script doesn't update other parametrers.  So if you are creating a database with non-default values, psql-consumer won't be able to login to database.
```
         # Update configuration
        sed -i -e "s/\([ ]*bootstrap.servers:\)\(.*\)/\1 \"${KAFKA_FQDN}\"/" /config/obmp-psql.yml
        sed -i -e "s/\([ ]*host[ ]*:\)\(.*\)/\1 \"${POSTGRES_HOST}\"/" /config/obmp-psql.yml

```
3. Is it possible to disable TLS/SSL on a psql-app ? I am getting the following error:
`org.postgresql.util.PSQLException: The server does not support SSL`

Thank you in advance.

**Comment by sydon7** [comment]
I submitted a pull request that includes the first item. 

For #2 are you in the psql-app container or the psql container (it looks like the psql-app container). Those variables seem to be working fine for me, I might not be looking at the same thing you are.

docker-compose.yml
  psql-app:
      - POSTGRES_PASSWORD=openbmp-test
      - POSTGRES_USER=openbmp-test
      - POSTGRES_DB=openbmp-test
      - POSTGRES_HOST=obmp-psql-test
      - POSTGRES_PORT=5433



docker exec -it obmp-psql-app bash
root@7437d476b66d:/tmp# env | grep POST
POSTGRES_HOST=obmp-psql-test
POSTGRES_PASSWORD=openbmp-test
POSTGRES_PORT=5433
POSTGRES_USER=openbmp-test
POSTGRES_DB=openbmp-test

**Comment by TimEvens** [comment]
Thank you for reporting. I'll update the run config to update the other vars.   The change to support TLS or not is on the PSQL container.   I'll add the config to configure SSL and SSL MODE.
